export const EErrorCode = {
  BAD_REQUEST: 'BAD_REQUEST',
  DEVELOPMENT_ERROR: 'DEVELOPMENT_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type TErrorCode = (typeof EErrorCode)[keyof typeof EErrorCode];
